name: open-calm-3b
seed: 42
zero_shot: true
huggingface_path: cyberagent/open-calm-3b
phase: dev
redundant_generation: true
confidence_threshold: 0.005
evaluation_batch_size: 8
evaluation_size: 4000
start_n: 1
evaluation_params:
  output_scores: true
  return_dict_in_generate: true
  do_sample: false
  top_k: 500
  top_p: 0.95
  max_new_tokens: 50
  num_beams:  5 # beam-search if >2
  num_return_sequences: 1 # need to be <= num_beams
device_map: 
  gpt_neox.embed_in: 0
  gpt_neox.layers.0: 1
  gpt_neox.layers.1: 1
  gpt_neox.layers.2: 1
  gpt_neox.layers.3: 1
  gpt_neox.layers.4: 1
  gpt_neox.layers.5: 1
  gpt_neox.layers.6: 1
  gpt_neox.layers.7: 1
  gpt_neox.layers.8: 1
  gpt_neox.layers.9: 1
  gpt_neox.layers.10: 1
  gpt_neox.layers.11: 1
  gpt_neox.layers.12: 1
  gpt_neox.layers.13: 1
  gpt_neox.layers.14: 1
  gpt_neox.layers.15: 1
  gpt_neox.layers.16: 1
  gpt_neox.layers.17: 1
  gpt_neox.layers.18: 1
  gpt_neox.layers.19: 1
  gpt_neox.layers.20: 1
  gpt_neox.layers.21: 1
  gpt_neox.layers.22: 1
  gpt_neox.layers.23: 1
  gpt_neox.layers.24: 1
  gpt_neox.layers.25: 1
  gpt_neox.layers.26: 1
  gpt_neox.layers.27: 1
  gpt_neox.layers.28: 1
  gpt_neox.layers.29: 1
  gpt_neox.layers.30: 1
  gpt_neox.layers.31: 1
  gpt_neox.final_layer_norm: 1
  embed_out: 1